export default {
    AUTH_STARTED:'AUTH_STARTED',
    AUTH_SUCCEEDED:'AUTH_SUCCEEDED',
    AUTH_FAILED:'AUTH_FAILED',
    AUTH_LOGOUT:'AUTH_LOGOUT',
    PLAYING:'PLAYING',
    PAUSED:'PAUSED',
    SLAVE_LINK:'SLAVE_LINK',
    UPDATE_GID:'UPDATE_GID',
    DELETE_GID:'DELETE_GID',
    UPDATE_QUEUE:'UPDATE_QUEUE',
    INIT_SLAVE_STARTED:'INIT_SLAVE_STARTED',
    INIT_SLAVE_SUCCEEDED:'INIT_SLAVE_SUCCEEDED',
    INIT_SLAVE_FAILED:'INIT_SLAVE_FAILED'
  };
  