export default {
    PUBLISHING_MESSAGE: 'PUBLISHING_MESSAGE',
    RECEIVING_MESSAGE: 'RECEIVING_MESSAGE',
    JOINING_GROUP: 'JOINING_GROUP',
    LEAVING_GROUP: 'LEAVING_GROUP',
    PICKING_NEXT_SONG: 'PICKING_NEXT_SONG',
  };
  