export default {
    AUTH_STARTED:'AUTH_STARTED',
    AUTH_SUCCEEDED:'AUTH_SUCCEEDED',
    AUTH_FAILED:'AUTH_FAILED',
    PLAYING:'PLAYING',
    PAUSED:'PAUSED',
    SLAVE_LINK:'SLAVE_LINK'
    
  };
  